export const TIPTAP = {
  BIAS: {
    FETCHING: 'TIPTAP/BIAS/FETCHING',
    RESULT: 'TIPTAP/BIAS/RESULT',
    MATCH: 'TIPTAP/BIAS/MATCH',
  },
  LANGUAGE: {
    FETCHING: 'TIPTAP/LANGUAGE/FETCHING',
    RESULT: 'TIPTAP/LANGUAGE/RESULT',
    MATCH: 'TIPTAP/LANGUAGE/MATCH',
  },
}

export const FIREBASE = {
  ANALYTICS: {
    BIAS: {
      FETCHED: 'FIREBASE/ANALYTICS/BIAS/FETCHED',
      CREATED: 'FIREBASE/ANALYTICS/BIAS/CREATED',
      UPDATED: 'FIREBASE/ANALYTICS/BIAS/UPDATED',
      ERROR: 'FIREBASE/ANALYTICS/BIAS/ERROR',
    },
  },

  AUTH: {
    CLEVER: {
      LOGIN_POPUP: 'FIREBASE/CLEVER/LOGIN_POPUP',
    },
  },
}

export function logger(type: string, data?: any) {
  console.log(type, data)
}
